### ISSUE TITLE
Accept offer URL needs to update after Make Offer button is clicked

### ISSUE THREAD

**Issue by isaacknjama** [civkit/civkit-frontend#34]
![image](https://github.com/user-attachments/assets/79731791-9236-4fec-ad5c-0f6b95764b29)

Within the accept offer URL column, the url for the order taker is saved. 

it is saved AFTER the make-offer button is hit in the ui. the acept offer url is dependent on the maker hitting make offer in the chat ui (/make-offer?orderId)

the problem is the UI is displaying the NON updated version of the acept offer url.

the backend is updating the databse, but the frontend is not displaying the latest version of the accept_offer_url

within the frontend, in the orders page, we need to investigate the OPEN CHAT BUTTON, specifically accept offer url and had a 2nd call to retrieve the latestet entry in the database from accept offer url column

1. accept offer url in db is updated on BE
2. orders page is not fetching the updated accept offer url column

We need to fix this so that users who take orders can reliably enter the chatroom

**Comment by MarketMadi** [comment]
resolved in pr chat-debug-2

will close when that is landed


before closing add these 2 issues to issues list:
need middleware to block accept offer from wrong user
its redirecting to localhost and not civkit.chat.africa

**Comment by MarketMadi** [comment]
completed, both issues fixed
