### ISSUE TITLE
There is no redirect from chat which means users need to be told to manually go to a url

### ISSUE THREAD

**Issue by isaacknjama** [civkit/civkit-frontend#35]
If I am the taker of a buy order, I need a redirect button in the chat to the `fiat-received` page, and then I should be redirected to the `trade-complete` page.

If I am the maker of a buy order, I need to be redirected to the `trade-complete` page.

If I am the maker of a sell order, I need to be redirected to the `fiat-received` page, and then I should be redirected to the `trade-complete` page.

If I am the taker of a sell order, I need to be redirected to the `trade-complete` page.

https://github.com/civkit/civkit-chat/blob/main/views/chatroom.pug
https://github.com/civkit/civkit-chat/blob/main/prisma/schema.prisma

**Comment by MarketMadi** [comment]
fixed
